FROM node:10.14.0
RUN mkdir -p /home/node/app/node_modules
RUN chown -R node:node /home/node/app
RUN npm i -g @adonisjs/cli

WORKDIR /home/node/app
COPY / /home/node/app
RUN npm install
COPY --chown=node:node . .
# RUN scripts
USER node
EXPOSE 3333
CMD ["npm","start"]
